### ISSUE TITLE
Idea: Download non-free game icons

### ISSUE THREAD

**Issue by lxndr** [lxndr/gswatcher#18]
Currently, I don't ship non-free game icons even though they are in the source code. Maybe, it's better to download some of they from Steam CDN?

**Comment by lxndr** [comment]
Hi! Thanks for the suggestion.

**Comment by lxndr** [comment]
So, instead of making the app to download each non-free icon at runtime, I simply separated them into a different repository. Now, for example, flatpak can download them during installation using `extra-data` option.

**Comment by dgibbs64** [comment]
I am running the windows version and cant see how to get the icons.

**Comment by dgibbs64** [comment]
Also by definition, all game icons are non-free and trademarks of their respective games. Including the ones you downloaded from sites claiming to be free. All the game icons should be OK under fair use https://en.wikipedia.org/wiki/Fair_use

**Comment by lxndr** [comment]
> I am running the windows version and cant see how to get the icons.

You can download them manually from https://github.com/lxndr/gswatcher-nonfree-icons/releases/download/v1.7.1/nonfree-icons.tar.gz and unpack to `usr/share/gswatcher/icons`. I'm a Linux user, so I didn't think about the Windows version too much. Additionally, I'm using GTK4 libraries, which are not really good for building a Windows app, unfortunately.

> Also by definition, all game icons are "non-free" and trademarks of their respective games. Including the ones you downloaded from sites claiming to be free. All the game icons should be OK to use under fair use https://en.wikipedia.org/wiki/Fair_use. Personally, I wouldn't get caught up on separating "non-free" icons as all you have actually done is distribute the icons via a different repo instead. Why not just put them all in the same repo and distribute as part of the application rather than adding extra steps? So in my opinion you either have the icons in your application or you have no icons at all as putting them in a different repo makes no realy difference.

I'm really not sure about how icon licensing works, and I've spent little time investigating this. Also, I'm probably overthinking it by separating the icon package for an app that most likely only has 5 users :D. I simply decided to play it safe and take the approach Flathub adopted. That means that the distribution archives only have artwork that can be freely shared (by its license) and some automatic instructions on where to download the rest of the icons.

**Comment by dgibbs64** [comment]
Yes I think the short answer is you are overthinking it 😄
